name: "Building"
description: "Compiles the project"

runs:
  using: "composite"
  steps:
    
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential git ninja-build
        
    - name: Install Conan
      shell: bash
      run: |
            pip3 install conan==2.4.1
        
    - name: Setup Conan profile
      shell: bash
      run: |
            conan profile detect --force
        
    - name: Install dependencies with Conan
      shell: bash
      run: |
            mkdir -p build
            cd build
            conan install .. --output-folder=. --build=missing
        
    - name: Build main project
      shell: bash
      run: |
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON
            cmake --build .
